package com.gcit.lms.entities;

// Generated Feb 5, 2014 2:59:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblBookCopies generated by hbm2java
 */
@Entity
@Table(name = "tbl_book_copies", catalog = "library")
public class BookCopies implements java.io.Serializable {

	private BookCopiesId id;
	private LibraryBranch tblLibraryBranch;
	private Book tblBook;
	private Integer noOfCopies;

	public BookCopies() {
	}

	public BookCopies(BookCopiesId id, LibraryBranch tblLibraryBranch,
			Book tblBook) {
		this.id = id;
		this.tblLibraryBranch = tblLibraryBranch;
		this.tblBook = tblBook;
	}

	public BookCopies(BookCopiesId id, LibraryBranch tblLibraryBranch,
			Book tblBook, Integer noOfCopies) {
		this.id = id;
		this.tblLibraryBranch = tblLibraryBranch;
		this.tblBook = tblBook;
		this.noOfCopies = noOfCopies;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "bookId", nullable = false)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branchId", nullable = false)) })
	public BookCopiesId getId() {
		return this.id;
	}

	public void setId(BookCopiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getTblLibraryBranch() {
		return this.tblLibraryBranch;
	}

	public void setTblLibraryBranch(LibraryBranch tblLibraryBranch) {
		this.tblLibraryBranch = tblLibraryBranch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookId", nullable = false, insertable = false, updatable = false)
	public Book getTblBook() {
		return this.tblBook;
	}

	public void setTblBook(Book tblBook) {
		this.tblBook = tblBook;
	}

	@Column(name = "noOfCopies")
	public Integer getNoOfCopies() {
		return this.noOfCopies;
	}

	public void setNoOfCopies(Integer noOfCopies) {
		this.noOfCopies = noOfCopies;
	}

}
