package com.gcit.lms.entities;

// Generated Feb 5, 2014 2:59:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblBookRequestsId generated by hbm2java
 */
@Embeddable
public class BookRequestsId implements java.io.Serializable {

	private int fromBranch;
	private int toBranch;
	private int itemId;
	private Date dateIn;

	public BookRequestsId() {
	}

	public BookRequestsId(int fromBranch, int toBranch, int itemId,
			Date dateIn) {
		this.fromBranch = fromBranch;
		this.toBranch = toBranch;
		this.itemId = itemId;
		this.dateIn = dateIn;
	}

	@Column(name = "fromBranch", nullable = false)
	public int getFromBranch() {
		return this.fromBranch;
	}

	public void setFromBranch(int fromBranch) {
		this.fromBranch = fromBranch;
	}

	@Column(name = "toBranch", nullable = false)
	public int getToBranch() {
		return this.toBranch;
	}

	public void setToBranch(int toBranch) {
		this.toBranch = toBranch;
	}

	@Column(name = "itemID", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "dateIn", nullable = false, length = 19)
	public Date getDateIn() {
		return this.dateIn;
	}

	public void setDateIn(Date dateIn) {
		this.dateIn = dateIn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookRequestsId))
			return false;
		BookRequestsId castOther = (BookRequestsId) other;

		return (this.getFromBranch() == castOther.getFromBranch())
				&& (this.getToBranch() == castOther.getToBranch())
				&& (this.getItemId() == castOther.getItemId())
				&& ((this.getDateIn() == castOther.getDateIn()) || (this
						.getDateIn() != null && castOther.getDateIn() != null && this
						.getDateIn().equals(castOther.getDateIn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFromBranch();
		result = 37 * result + this.getToBranch();
		result = 37 * result + this.getItemId();
		result = 37 * result
				+ (getDateIn() == null ? 0 : this.getDateIn().hashCode());
		return result;
	}

}
