package com.gcit.lms.entities;

// Generated Feb 5, 2014 2:59:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBookRequests generated by hbm2java
 */
@Entity
@Table(name = "tbl_book_requests", catalog = "library")
public class BookRequests implements java.io.Serializable {

	private BookRequestsId id;
	private LibraryBranch tblLibraryBranchByFromBranch;
	private LibraryBranch tblLibraryBranchByToBranch;
	private Book tblBook;
	private Integer noOfItems;
	private Date dateApproved;

	public BookRequests() {
	}

	public BookRequests(BookRequestsId id,
			LibraryBranch tblLibraryBranchByFromBranch,
			LibraryBranch tblLibraryBranchByToBranch, Book tblBook) {
		this.id = id;
		this.tblLibraryBranchByFromBranch = tblLibraryBranchByFromBranch;
		this.tblLibraryBranchByToBranch = tblLibraryBranchByToBranch;
		this.tblBook = tblBook;
	}

	public BookRequests(BookRequestsId id,
			LibraryBranch tblLibraryBranchByFromBranch,
			LibraryBranch tblLibraryBranchByToBranch, Book tblBook,
			Integer noOfItems, Date dateApproved) {
		this.id = id;
		this.tblLibraryBranchByFromBranch = tblLibraryBranchByFromBranch;
		this.tblLibraryBranchByToBranch = tblLibraryBranchByToBranch;
		this.tblBook = tblBook;
		this.noOfItems = noOfItems;
		this.dateApproved = dateApproved;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fromBranch", column = @Column(name = "fromBranch", nullable = false)),
			@AttributeOverride(name = "toBranch", column = @Column(name = "toBranch", nullable = false)),
			@AttributeOverride(name = "itemId", column = @Column(name = "itemID", nullable = false)),
			@AttributeOverride(name = "dateIn", column = @Column(name = "dateIn", nullable = false, length = 19)) })
	public BookRequestsId getId() {
		return this.id;
	}

	public void setId(BookRequestsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fromBranch", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getTblLibraryBranchByFromBranch() {
		return this.tblLibraryBranchByFromBranch;
	}

	public void setTblLibraryBranchByFromBranch(
			LibraryBranch tblLibraryBranchByFromBranch) {
		this.tblLibraryBranchByFromBranch = tblLibraryBranchByFromBranch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "toBranch", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getTblLibraryBranchByToBranch() {
		return this.tblLibraryBranchByToBranch;
	}

	public void setTblLibraryBranchByToBranch(
			LibraryBranch tblLibraryBranchByToBranch) {
		this.tblLibraryBranchByToBranch = tblLibraryBranchByToBranch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemID", nullable = false, insertable = false, updatable = false)
	public Book getTblBook() {
		return this.tblBook;
	}

	public void setTblBook(Book tblBook) {
		this.tblBook = tblBook;
	}

	@Column(name = "noOfItems")
	public Integer getNoOfItems() {
		return this.noOfItems;
	}

	public void setNoOfItems(Integer noOfItems) {
		this.noOfItems = noOfItems;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateApproved", length = 19)
	public Date getDateApproved() {
		return this.dateApproved;
	}

	public void setDateApproved(Date dateApproved) {
		this.dateApproved = dateApproved;
	}

}
