package com.gcit.lms.entities;

// Generated Feb 5, 2014 2:59:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblLibraryBranch generated by hbm2java
 */
@Entity
@Table(name = "tbl_library_branch", catalog = "library")
public class LibraryBranch implements java.io.Serializable {

	private Integer branchId;
	private String branchName;
	private String branchAddress;
	private Set<Reservation> tblReservations = new HashSet<Reservation>(0);
	private Set<BookRequests> tblBookRequestsesForFromBranch = new HashSet<BookRequests>(
			0);
	private Set<BookLoans> tblBookLoanses = new HashSet<BookLoans>(0);
	private Set<BookRequests> tblBookRequestsesForToBranch = new HashSet<BookRequests>(
			0);
	private Set<BookCopies> tblBookCopieses = new HashSet<BookCopies>(0);
	private Set<Librarian> tblLibrarians = new HashSet<Librarian>(0);

	public LibraryBranch() {
	}

	public LibraryBranch(String branchName, String branchAddress,
			Set<Reservation> tblReservations,
			Set<BookRequests> tblBookRequestsesForFromBranch,
			Set<BookLoans> tblBookLoanses,
			Set<BookRequests> tblBookRequestsesForToBranch,
			Set<BookCopies> tblBookCopieses, Set<Librarian> tblLibrarians) {
		this.branchName = branchName;
		this.branchAddress = branchAddress;
		this.tblReservations = tblReservations;
		this.tblBookRequestsesForFromBranch = tblBookRequestsesForFromBranch;
		this.tblBookLoanses = tblBookLoanses;
		this.tblBookRequestsesForToBranch = tblBookRequestsesForToBranch;
		this.tblBookCopieses = tblBookCopieses;
		this.tblLibrarians = tblLibrarians;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "branchId", unique = true, nullable = false)
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "branchName", length = 45)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "branchAddress", length = 45)
	public String getBranchAddress() {
		return this.branchAddress;
	}

	public void setBranchAddress(String branchAddress) {
		this.branchAddress = branchAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<Reservation> getTblReservations() {
		return this.tblReservations;
	}

	public void setTblReservations(Set<Reservation> tblReservations) {
		this.tblReservations = tblReservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranchByFromBranch")
	public Set<BookRequests> getTblBookRequestsesForFromBranch() {
		return this.tblBookRequestsesForFromBranch;
	}

	public void setTblBookRequestsesForFromBranch(
			Set<BookRequests> tblBookRequestsesForFromBranch) {
		this.tblBookRequestsesForFromBranch = tblBookRequestsesForFromBranch;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<BookLoans> getTblBookLoanses() {
		return this.tblBookLoanses;
	}

	public void setTblBookLoanses(Set<BookLoans> tblBookLoanses) {
		this.tblBookLoanses = tblBookLoanses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranchByToBranch")
	public Set<BookRequests> getTblBookRequestsesForToBranch() {
		return this.tblBookRequestsesForToBranch;
	}

	public void setTblBookRequestsesForToBranch(
			Set<BookRequests> tblBookRequestsesForToBranch) {
		this.tblBookRequestsesForToBranch = tblBookRequestsesForToBranch;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<BookCopies> getTblBookCopieses() {
		return this.tblBookCopieses;
	}

	public void setTblBookCopieses(Set<BookCopies> tblBookCopieses) {
		this.tblBookCopieses = tblBookCopieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<Librarian> getTblLibrarians() {
		return this.tblLibrarians;
	}

	public void setTblLibrarians(Set<Librarian> tblLibrarians) {
		this.tblLibrarians = tblLibrarians;
	}

}
